name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

env:
  GO_VERSION: '1.22'
  BINARY_NAME: open_tool_speex

jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: open_tool_speex-linux
          - os: macos-latest
            platform: macos
            artifact_name: open_tool_speex-macos
          - os: windows-latest
            platform: windows
            artifact_name: open_tool_speex.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libspeexdsp-dev pkg-config

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install speexdsp pkg-config
        # Verify installation
        pkg-config --cflags speexdsp
        pkg-config --libs speexdsp

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Install pkg-config for Windows
        choco install pkgconfiglite -y
        # Add pkg-config to PATH
        echo "C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\bin" >> $GITHUB_PATH
        # Install MSYS2 for development tools
        choco install msys2 -y
        # Install vcpkg manually
        git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        .\bootstrap-vcpkg.bat
        # Add vcpkg to PATH
        echo "C:\vcpkg" >> $GITHUB_PATH

    - name: Install Task
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          # Download Task binary directly for Windows
          curl -L https://github.com/go-task/task/releases/download/v3.35.0/task_windows_amd64.zip -o task.zip
          unzip -o task.zip
          chmod +x task.exe
          # Add to PATH for current session
          echo "$PWD" >> $GITHUB_PATH
          # Copy to a location in PATH
          cp task.exe /usr/local/bin/task || cp task.exe /usr/bin/task || cp task.exe /bin/task
        else
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
        fi

    - name: Build all platforms
      shell: bash
      run: |
        # Set environment variables for CGO
        export CGO_ENABLED=1
        if [ "$RUNNER_OS" = "Windows" ]; then
          # Set environment variables for Windows CGO
          export PKG_CONFIG_PATH="/c/vcpkg/installed/x64-windows/lib/pkgconfig"
          export CGO_CFLAGS="-I/c/vcpkg/installed/x64-windows/include"
          export CGO_LDFLAGS="-L/c/vcpkg/installed/x64-windows/lib"
          # Install SpeexDSP via vcpkg
          vcpkg install speexdsp:x64-windows
        elif [ "$RUNNER_OS" = "macOS" ]; then
          # Set environment variables for macOS CGO
          export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig"
        fi
        task build-all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: build/${{ env.BINARY_NAME }}*

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Prepare release assets
      run: |
        mkdir -p release
        find . -name "open_tool_speex*" -type f -exec cp {} release/ \;
        ls -la release/

    - name: Generate changelog
      id: changelog
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          TAG=${{ github.ref_name }}
        else
          TAG=${{ github.event.inputs.tag }}
        fi
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        
        # Generate changelog from git commits
        echo "## Changes in $TAG" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "## Installation" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "Download the appropriate binary for your platform:" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "- **Linux**: \`open_tool_speex-linux\`" >> CHANGELOG.md
        echo "- **macOS**: \`open_tool_speex-macos\`" >> CHANGELOG.md
        echo "- **Windows**: \`open_tool_speex.exe\`" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "## Usage" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "\`\`\`bash" >> CHANGELOG.md
        echo "./open_tool_speex -mic input.alaw -speaker reference.alaw -output output.alaw" >> CHANGELOG.md
        echo "\`\`\`" >> CHANGELOG.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        name: Release ${{ steps.changelog.outputs.tag }}
        body_path: CHANGELOG.md
        files: |
          release/open_tool_speex-linux
          release/open_tool_speex-macos
          release/open_tool_speex.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
